---
title: "cooccurance_words"
author: "Goutham"
date: "5/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

### Finding simimlar words that occur together in a document
# tdm and dtm from similarity_tutorial.Rmd file

```{r libraries and data}
# https://www.worldfullofdata.com/text-mining-analysis-including-full-code-r/
rm(list = ls())

require("tm")
require("magrittr")
my.corpus <- Corpus(DirSource("r-corpus"))
```

```{r transformations}
skipWords <- function(x) removeWords(x, stopwords("english"))
my.corpus <- tm_map(my.corpus, FUN = tm_reduce, tmFuns = list(tolower, skipWords, removePunctuation,
                                                              stripWhitespace, removeNumbers))

inspect(my.corpus[1])
```

```{r tdm and dtm}
# t(tdm) = dtm and vice versa

my.tdm <- TermDocumentMatrix(my.corpus)
my.dtm <- DocumentTermMatrix(my.corpus)

inspect(my.tdm)
inspect(my.dtm) # 90% sparse – meaning that 90% of its cells are either not filled with data or are zeros

as.matrix(my.tdm[,]) %>% View()
as.matrix(my.dtm[,]) %>% View()

uni.words <- colnames(my.dtm)
uni.words %>% View()

```

```{r text mining}
dim(my.dtm) # rows are unique terms
attributes(my.dtm)
attributes(my.dtm$dimnames)
my.dtm$dimnames$Terms[1:20] # returns words in ascending order

inspect(removeSparseTerms(my.dtm, 0.50)) # keep all terms which appear in 50% of the documents
findFreqTerms(my.dtm, 15)
findMostFreqTerms(my.dtm, n = 5)

findAssocs(my.dtm, c("psychiatry"), 0.5)[[1]][1:5] # find co-occurrences of a word using correlation
```

```{r freq table}
freq.mat <- as.matrix(my.tdm) # or t(as.matrix(my.dtm))
freq.tab <- data.frame(term = rownames(freq.mat), freq = rowSums(freq.mat), row.names = NULL)
freq.tab <- freq.tab[order(-freq.tab$freq),][1:10,]

freq.tab %>% View()
```

```{r freq plot}
require("ggplot2")
freq.plot <- ggplot(freq.tab, aes(x = reorder(term, -freq), freq)) +
  geom_bar(stat = "identity", fill = "lightblue") +
  labs(x = "terms", y = "frequency", title = "Frequent words") +
  geom_text(aes(label = freq), vjust = -0.5, size = 3) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +

freq.plot
```

```{r co-occurance heatmap}

```

