---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

### N-grams

```{r}
# https://rstudio-pubs-static.s3.amazonaws.com/118348_a00ba585d2314b3c937d6acd4f4698b0.html
rm(list = ls())
options(mc.cores=1)

library(tm)
library(ggplot2)
library(reshape2)
library(wordcloud)
library(magrittr)
```

```{r}
path = "./r-corpus"
dir = DirSource(paste(path,sep=""), encoding = "UTF-8")

my.corpus = VCorpus(dir)
```

```{r}
my.corpus.ng = tm_map(my.corpus,removeWords,c(stopwords(),"s","ve"))
my.corpus.ng = tm_map(my.corpus.ng,removePunctuation)
my.corpus.ng = tm_map(my.corpus.ng,removeNumbers)

```

```{r}
bi.token <- function(x) {RWeka::NGramTokenizer(x, RWeka::Weka_control(min = 2, max = 2))}
tdm.bigram = TermDocumentMatrix(my.corpus.ng, control = list(tokenize = bi.token))
as.matrix(tdm.bigram) %>% View()

```

```{r}
freq = sort(rowSums(as.matrix(tdm.bigram)),decreasing = TRUE)
freq.df = data.frame(word=names(freq), freq=freq)
head(freq.df, 20)

```

```{r}
pal=brewer.pal(8,"Blues")
pal=pal[-(1:3)]
wordcloud(freq.df$word,freq.df$freq,max.words=100,random.order = F, colors=pal)
```

```{r}
require(ggplot2)

ggplot(head(freq.df,15), aes(reorder(word,freq), freq)) +
  geom_bar(stat = "identity") + coord_flip() +
  xlab("Bigrams") + ylab("Frequency") +
  ggtitle("Most frequent bigrams")

```






